server:
  port: 8765
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: default
          uri: "*"
          predicates:
          - Path=/**
          filters:
          -name: CircuitBreaker
          args:
            name: CircuitBreakerFallback
            fallbackUri: forward:/fallback
